name: push

on:
  push:
    branches: [ tmp/bug-fix ]
    tags:
    - '*'

jobs:
  push:
    permissions:
      contents: read
      packages: write
    name: push
    if: github.repository_owner == 'backjo'
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        version: latest

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: false

    -
      name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/instance-manager
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: master

